server:
  port: 8080

spring:
  application:
    name: activiti
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.bwin.activitidemo.entity
  global-config:
    db-config:
      id-type: ID_WORKER_STR
      column-like: true

logging:
  file: ./logs/${spring.application.name}.log
  level:
    com.bwin.activitidemo:
      mapper: DEBUG